//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetDotnetFramework.Api.BarcodeReader {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BarcodeReader.IBarcodeReaderService")]
    public interface IBarcodeReaderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarcodeReaderService/GetDataMatrixText", ReplyAction="http://tempuri.org/IBarcodeReaderService/GetDataMatrixTextResponse")]
        string GetDataMatrixText(byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarcodeReaderService/GetDataMatrixText", ReplyAction="http://tempuri.org/IBarcodeReaderService/GetDataMatrixTextResponse")]
        System.Threading.Tasks.Task<string> GetDataMatrixTextAsync(byte[] image);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBarcodeReaderServiceChannel : ProjetDotnetFramework.Api.BarcodeReader.IBarcodeReaderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BarcodeReaderServiceClient : System.ServiceModel.ClientBase<ProjetDotnetFramework.Api.BarcodeReader.IBarcodeReaderService>, ProjetDotnetFramework.Api.BarcodeReader.IBarcodeReaderService {
        
        public BarcodeReaderServiceClient() {
        }
        
        public BarcodeReaderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BarcodeReaderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarcodeReaderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarcodeReaderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDataMatrixText(byte[] image) {
            return base.Channel.GetDataMatrixText(image);
        }
        
        public System.Threading.Tasks.Task<string> GetDataMatrixTextAsync(byte[] image) {
            return base.Channel.GetDataMatrixTextAsync(image);
        }
    }
}
